name: Packer Application Check
on:
  pull_request:
    branches: [main]
env:
  AMI_USER: ${{ secrets.AMI_USER }}

jobs:
  packer-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clean install
        run: npm ci

      - name: Zip Files
        run: zip -r webapp.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer Init
        run: packer init .

      - name: Packer Validate
        run: packer validate .

      - name: Packer Build
        run: LATEST_AMI_ID=$(packer build -machine-readable . | awk -F, '$0 ~/artifact,0,id/ {print $6}')

      - name: Get Launch Configuration Details
        run: LC_DETAILS=$(aws autoscaling describe-launch-configurations --launch-configuration-names $$LATEST_LAUNCH_TEMPLATE_ID)
          LC_CONFIG=$(echo $LC_DETAILS | jq 'del(.LaunchConfigurations[].ImageId)')

      - name: Create Launch Configuration Version
        run: aws autoscaling create-launch-configuration --launch-configuration-name $NEW_LC_NAME --launch-configuration $LC_CONFIG --image-id $LATEST_AMI_ID

      - name: Update Auto Scaling Group
        run: aws autoscaling update-auto-scaling-group --auto-scaling-group-name ${{secrets.AUTO_SCALING_GROUP_NAME}} --launch-template LaunchTemplateName=${{secrets.LT_NAME}},Version='$Latest'

      - name: Start Instance Refresh
        run: aws autoscaling start-instance-refresh --auto-scaling-group-name ${{secrets.AUTO_SCALING_GROUP_NAME}}
