name: Packer Application Check
on:
  pull_request:
    branches: [main]
env:
  AMI_USER: ${{ secrets.AMI_USER }}

jobs:
  packer-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clean install
        run: npm ci

      - name: Zip Files
        run: zip -r webapp.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer Init
        run: packer init .

      - name: Packer Validate
        run: packer validate .

      - name: Packer Build
        run: LATEST_AMI_ID=$(packer build -machine-readable . | awk -F, '$0 ~/artifact,0,id/ {print $6}')
              echo "${{ LATEST_AMI_ID }}"

      - name: Get Launch Template ID
        run: |
          LATEST_LAUNCH_TEMPLATE_ID=$(aws ec2 describe-launch-templates --filters "Name=launch-template-name,Values=${{ secrets.LAUNCH_TEMPLATE_NAME}}" --query "LaunchTemplates[0].LaunchTemplateId" --output text)
          echo "${{LATEST_LAUNCH_TEMPLATE_ID }}"
          aws ec2 create-launch-template-version --launch-template-id $LATEST_LAUNCH_TEMPLATE_ID --source-version '$Latest' --launch-template-data '{"ImageId":"'"$LATEST_AMI_ID"'"}'  --region ${{ secrets.AWS_REGION }}
          
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name ${{secrets.AUTO_SCALING_GROUP_NAME}} --launch-template LaunchTemplateName=${{secrets.LT_NAME}},Version='$Latest'
          aws autoscaling start-instance-refresh --auto-scaling-group-name ${{secrets.AUTO_SCALING_GROUP_NAME}}

2
