name: Packer Application Check
on:
  pull_request:
    branches: [main]
env:
  AMI_USER: ${{ secrets.AMI_USER }}

jobs:
  packer-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clean install
        run: npm ci

      - name: Zip Files
        run: zip -r webapp.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer Init
        run: packer init .

      - name: Packer Validate
        run: packer validate .

      - name: Packer Build
        run: packer build -machine-readable .
          LATEST_AMI_ID=$(packer build -machine-readable . | awk -F, '$0 ~/artifact,0,id/ {print $6}')

      - name: Get Launch Template ID
        run: |
          LAUNCH_TEMPLATE_NAME="asg_launch_config"
          LATEST_LAUNCH_TEMPLATE_ID=$(aws ec2 describe-launch-templates --filters "Name=launch-template-name,Values=$LAUNCH_TEMPLATE_NAME" --query "LaunchTemplates[0].LaunchTemplateId" --output text)
          aws ec2 create-launch-template-version --launch-template-id $LATEST_LAUNCH_TEMPLATE_ID --source-version $LATEST_LAUNCH_TEMPLATE_ID --image-id $LATEST_AMI_ID --region ${{ secrets.AWS_REGION }}



